version: '3.8'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    logging:
      driver: none
      
  sourceta-backend:
    build: .
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: "uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
    # tty: true
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./
        target: /code
    tty: true

volumes:
  mongodb_data_container:
